package com.tmt.cognitive.challenge.visualrecognition.vo;

// Generated Oct 27, 2017 5:49:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commercialproductsprofile generated by hbm2java
 */
@Entity
@Table(name = "commercialproductsprofile")
public class Commercialproductsprofile implements java.io.Serializable {

	private Long productid;
	private String productname;
	private String productdescription;
	private Date createdtime;
	private String createdby;
	private Date updatedtime;
	private String udpatedby;
	private Set<Userproductscoremapping> userproductscoremappings = new HashSet<Userproductscoremapping>(
			0);
	private Set<Visualrecognitionaudittransaction> visualrecognitionaudittransactions = new HashSet<Visualrecognitionaudittransaction>(
			0);
	private Set<Userproductadsmapping> userproductadsmappings = new HashSet<Userproductadsmapping>(
			0);

	public Commercialproductsprofile() {
	}

	public Commercialproductsprofile(String productname) {
		this.productname = productname;
	}

	public Commercialproductsprofile(
			String productname,
			String productdescription,
			Date createdtime,
			String createdby,
			Date updatedtime,
			String udpatedby,
			Set<Userproductscoremapping> userproductscoremappings,
			Set<Visualrecognitionaudittransaction> visualrecognitionaudittransactions,
			Set<Userproductadsmapping> userproductadsmappings) {
		this.productname = productname;
		this.productdescription = productdescription;
		this.createdtime = createdtime;
		this.createdby = createdby;
		this.updatedtime = updatedtime;
		this.udpatedby = udpatedby;
		this.userproductscoremappings = userproductscoremappings;
		this.visualrecognitionaudittransactions = visualrecognitionaudittransactions;
		this.userproductadsmappings = userproductadsmappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PRODUCTID", unique = true, nullable = false)
	public Long getProductid() {
		return this.productid;
	}

	public void setProductid(Long productid) {
		this.productid = productid;
	}

	@Column(name = "PRODUCTNAME", nullable = false, length = 200)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "PRODUCTDESCRIPTION", length = 1000)
	public String getProductdescription() {
		return this.productdescription;
	}

	public void setProductdescription(String productdescription) {
		this.productdescription = productdescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDTIME", length = 19)
	public Date getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	@Column(name = "CREATEDBY", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEDTIME", length = 19)
	public Date getUpdatedtime() {
		return this.updatedtime;
	}

	public void setUpdatedtime(Date updatedtime) {
		this.updatedtime = updatedtime;
	}

	@Column(name = "UDPATEDBY", length = 45)
	public String getUdpatedby() {
		return this.udpatedby;
	}

	public void setUdpatedby(String udpatedby) {
		this.udpatedby = udpatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commercialproductsprofile")
	public Set<Userproductscoremapping> getUserproductscoremappings() {
		return this.userproductscoremappings;
	}

	public void setUserproductscoremappings(
			Set<Userproductscoremapping> userproductscoremappings) {
		this.userproductscoremappings = userproductscoremappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commercialproductsprofile")
	public Set<Visualrecognitionaudittransaction> getVisualrecognitionaudittransactions() {
		return this.visualrecognitionaudittransactions;
	}

	public void setVisualrecognitionaudittransactions(
			Set<Visualrecognitionaudittransaction> visualrecognitionaudittransactions) {
		this.visualrecognitionaudittransactions = visualrecognitionaudittransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commercialproductsprofile")
	public Set<Userproductadsmapping> getUserproductadsmappings() {
		return this.userproductadsmappings;
	}

	public void setUserproductadsmappings(
			Set<Userproductadsmapping> userproductadsmappings) {
		this.userproductadsmappings = userproductadsmappings;
	}

}
