package com.tmt.cognitive.challenge.visualrecognition.vo;

// Generated Oct 27, 2017 5:49:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visualrecognisionuserprofiles generated by hbm2java
 */
@Entity
@Table(name = "visualrecognisionuserprofiles")
public class Visualrecognisionuserprofiles implements java.io.Serializable {

	private Long userprofileid;
	private int minimumage;
	private Integer maximumage;
	private String gender;
	private Date createdtime;
	private String createdby;
	private Date updatedtime;
	private String updatedby;
	private Set<Userproductadsmapping> userproductadsmappings = new HashSet<Userproductadsmapping>(
			0);
	private Set<Userproductscoremapping> userproductscoremappings = new HashSet<Userproductscoremapping>(
			0);
	private Set<Visualrecognitionaudittransaction> visualrecognitionaudittransactions = new HashSet<Visualrecognitionaudittransaction>(
			0);

	public Visualrecognisionuserprofiles() {
	}

	public Visualrecognisionuserprofiles(int minimumage, String gender) {
		this.minimumage = minimumage;
		this.gender = gender;
	}

	public Visualrecognisionuserprofiles(
			int minimumage,
			Integer maximumage,
			String gender,
			Date createdtime,
			String createdby,
			Date updatedtime,
			String updatedby,
			Set<Userproductadsmapping> userproductadsmappings,
			Set<Userproductscoremapping> userproductscoremappings,
			Set<Visualrecognitionaudittransaction> visualrecognitionaudittransactions) {
		this.minimumage = minimumage;
		this.maximumage = maximumage;
		this.gender = gender;
		this.createdtime = createdtime;
		this.createdby = createdby;
		this.updatedtime = updatedtime;
		this.updatedby = updatedby;
		this.userproductadsmappings = userproductadsmappings;
		this.userproductscoremappings = userproductscoremappings;
		this.visualrecognitionaudittransactions = visualrecognitionaudittransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USERPROFILEID", unique = true, nullable = false)
	public Long getUserprofileid() {
		return this.userprofileid;
	}

	public void setUserprofileid(Long userprofileid) {
		this.userprofileid = userprofileid;
	}

	@Column(name = "MINIMUMAGE", nullable = false)
	public int getMinimumage() {
		return this.minimumage;
	}

	public void setMinimumage(int minimumage) {
		this.minimumage = minimumage;
	}

	@Column(name = "MAXIMUMAGE")
	public Integer getMaximumage() {
		return this.maximumage;
	}

	public void setMaximumage(Integer maximumage) {
		this.maximumage = maximumage;
	}

	@Column(name = "GENDER", nullable = false, length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDTIME", length = 19)
	public Date getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	@Column(name = "CREATEDBY", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEDTIME", length = 19)
	public Date getUpdatedtime() {
		return this.updatedtime;
	}

	public void setUpdatedtime(Date updatedtime) {
		this.updatedtime = updatedtime;
	}

	@Column(name = "UPDATEDBY", length = 45)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "visualrecognisionuserprofiles")
	public Set<Userproductadsmapping> getUserproductadsmappings() {
		return this.userproductadsmappings;
	}

	public void setUserproductadsmappings(
			Set<Userproductadsmapping> userproductadsmappings) {
		this.userproductadsmappings = userproductadsmappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "visualrecognisionuserprofiles")
	public Set<Userproductscoremapping> getUserproductscoremappings() {
		return this.userproductscoremappings;
	}

	public void setUserproductscoremappings(
			Set<Userproductscoremapping> userproductscoremappings) {
		this.userproductscoremappings = userproductscoremappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "visualrecognisionuserprofiles")
	public Set<Visualrecognitionaudittransaction> getVisualrecognitionaudittransactions() {
		return this.visualrecognitionaudittransactions;
	}

	public void setVisualrecognitionaudittransactions(
			Set<Visualrecognitionaudittransaction> visualrecognitionaudittransactions) {
		this.visualrecognitionaudittransactions = visualrecognitionaudittransactions;
	}

}
